name: convert-ip-task

on:
#  push: # push触发
#    branches: [ master ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '0 9 2 */4 *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时,如上表示每天14点10分

permissions:
  contents: write

jobs:
  run-convert-ip-list:

    runs-on: ubuntu-latest
    env:
      trigger: ${{ github.event_name }}
    steps:
    # 检出
    - name: Checkout
      uses: actions/checkout@v2

    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
    # 下载源仓库
    - name: Download
      run: wget https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt -O china_ip_list.txt.1
      
    - name: Diff or Workflow Dispatch
      id: diff
      run: |
        dff=$( diff ./china_ip_list.txt china_ip_list.txt.1 )
        if [ -z $dff ]; then
          continuing="no";
        else
          continuing="yes";
          mv china_ip_list.txt.1 china_ip_list.txt
          git add china_ip_list.txt
        fi
        echo "The trigger for this workflow is '"$trigger"'"
        if [ $trigger = "workflow_dispatch" ]; then
          continuing="yes";
        fi
        echo "continuing=$continuing" >> $GITHUB_OUTPUT

    - name: Convert to Surge Ruleset
      run: |
        echo "#The china ip list referred to https://github.com/17mon/china_ip_list" > surge_china_ip.list
        awk '{print "IP-CIDR,"$0}' china_ip_list.txt >> surge_china_ip.list
        git add surge_china_ip.list
      if: steps.diff.outputs.continuing == 'yes'
      
    - name: Convert to Clash rule provider
      run: |
        echo "#The china ip list referred to https://github.com/17mon/china_ip_list" > clash_cncidr.txt
        echo "payload:" >> clash_cncidr.txt
        awk '{print "  - '\''"$0"'\''"}' china_ip_list.txt >> clash_cncidr.txt
        git add clash_cncidr.txt
      if: steps.diff.outputs.continuing == 'yes'
      
    # 本地提交
    - name: Commit files
      if: steps.diff.outputs.continuing == 'yes'
      run: |
         git config --local user.email "ciaoly@github.com"
         git config --local user.name "ciaoly"
         git commit -m "文件更新于$(date "+%Y-%m-%d %H:%M:%S")"
         
    # 更新至远程github代码仓库中
    - name: Push changes
      uses: ad-m/github-push-action@master
      if: steps.diff.outputs.continuing == 'yes'
      with:
         github_token: ${{ secrets.CHNIP_GIT_KEY }}
         branch: master
